[workspace]
members = [
    "rust/core",
    "rust/serde_wormhole",
]

[profile.release]
opt-level = 3
lto = "thin"

[patch.crates-io]
serde_wormhole = { path = "./rust/serde_wormhole" }
wormhole-sdk = { path = "./rust/core" }
