[workspace]
members = [
    "serde_wormhole",
    "core",
]

[profile.release]
opt-level = 3
lto = "thin"

[patch.crates-io]
serde_wormhole = { path = "serde_wormhole" }
wormhole-sdk = { path = "core" }
