[workspace]
members = [
    "wormhole_sdk",
    "serde_wormhole",
]

[profile.release]
opt-level = 3
lto = "thin"

[patch.crates-io]
serde_wormhole = { path = "serde_wormhole" }
wormhole_sdk-sdk = { path = "wormhole_sdk" }
