---
protocol-key-pair:
  value: OXnx3yM1C/ppgnDMx/o1d49fJs7E05kq11mXNae/O+I=
worker-key-pair:
  value: AKt19CyPt+Hsvq7AvwZx2j/K7aRPgigtL4nCzgzytlA4
account-key-pair:
  value: AM/QIRQPH+PpIoMXdCj2jCPBuL1bJ+6wYgkk3RiK23dm
network-key-pair:
  value: AKGauInN9PIAGz1eXVqAikuBcMU8M8/k7PPQaIOzPv8p
db-path: sui_config/authorities_db/addeef94d898
network-address: /ip4/127.0.0.1/tcp/37177/http
json-rpc-address: "127.0.0.1:39753"
metrics-address: "127.0.0.1:34433"
admin-interface-port: 45401
consensus-config:
  address: /ip4/127.0.0.1/tcp/39729/http
  db-path: sui_config/consensus_db/addeef94d898
  internal-worker-address: ~
  max-pending-transactions: ~
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 2000ms
    min_header_delay: 500ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/38025/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/37969/http
    network_admin_server:
      primary_network_admin_server_port: 36271
      worker_network_admin_server_base_port: 34359
    anemo:
      send_certificate_rate_limit: ~
      get_payload_availability_rate_limit: ~
      get_certificates_rate_limit: ~
      report_batch_rate_limit: ~
      request_batch_rate_limit: ~
enable-event-processing: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:38239"
  external-address: /ip4/127.0.0.1/udp/38239
genesis:
  genesis-file-location: sui_config/genesis.blob
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 2
  max-checkpoints-in-batch: 200
  max-transactions-in-batch: 1000
  use-range-deletion: true
end-of-epoch-broadcast-channel-capacity: 128
checkpoint-executor-config:
  checkpoint-execution-max-concurrency: 200
  local-execution-timeout-sec: 10
db-checkpoint-config:
  perform-db-checkpoints-at-epoch-end: false
indirect-objects-threshold: 18446744073709551615
expensive-safety-check-config:
  enable-epoch-sui-conservation-check: false
  force-disable-epoch-sui-conservation-check: false
  enable-state-consistency-check: false
  force-disable-state-consistency-check: false
  enable-move-vm-paranoid-checks: false
